### ISSUE TITLE
Suggestion: Merchant 

### ISSUE THREAD

**Issue by HeberPcL** [JereKuusela/valheim-cron_job#1]
Hey man,

Do you think it would be possible to make the **Merchant disappear**, requiring the player to look for one of the spawns again?

**Your mod is very useful. Nice job!**

**Comment by JereKuusela** [comment]
Upgrade World mod allows this. Hover over the icon on the map and check zone indices at the top right corner.

Then use `zones_reset zone=i,j maxDistance=1 start force` where i and j are the zone indices. For example -67 and 22.

This resets the merchant zone and adjacent zones

**Comment by HeberPcL** [comment]
So, the interesting thing was being able to do this with CRON, for example every Sunday the Merchant would disappear. Or every x Days.

**Comment by JereKuusela** [comment]
Ok, that would need update to Upgrade World to allow placing locations on unexplored areas (since now it includes explores areas as well).

**locations_remove Vendor_BlackForest start force** can be used to remove it but then you would have to use **genloc** which is very slow.

**Comment by HeberPcL** [comment]
Excellent, thanks for the information. I leave it as a suggestion for the future. That would be really interesting.

And again, **Congratulations** for the great work.
