### ISSUE TITLE
Doesn't seem to be working in patch 0.214.2

### ISSUE THREAD

**Issue by Raakalainen** [JereKuusela/valheim-cron_job#12]
Had this working a couple days ago, informing me on discord about everyones names and steamids for easier server management.

But as the patch hit, cron seems to have gone mute and nothing seems to wake him up.

**Comment by Raakalainen** [comment]
and by informing me, I meant that my bots send chat to discord so I had all the info in that welcome text to work with.

sorry, tired and feel like after a wrestling match after getting everything else to work again :) 
thanks for the quick updates for the most essential admin tools, running servers would be so stale without em.

**Comment by JereKuusela** [comment]
Does the Discord mod otherwise work?

**Comment by Raakalainen** [comment]
Yes, discord mod works fine and cron also works very nicely now, thanks for the update.
