### ISSUE TITLE
CRON Jobs firing repeatedly instead of 1 per month

### ISSUE THREAD

**Issue by FractusLogicum** [JereKuusela/valheim-cron_job#13]
Discord Reports of CRON Jobs:
[Multi Run instead of monthly.txt](https://github.com/JereKuusela/valheim-cron_job/files/12242567/Multi.Run.instead.of.monthly.txt)

CRON.yaml set to fire once per month as per the suggested crontab.guru
[cron.yaml.txt](https://github.com/JereKuusela/valheim-cron_job/files/12242656/cron.yaml.txt)

Any ideas?

**Comment by JereKuusela** [comment]
You have set it run once per each zone  Check documentation about jobs vs zone

**Comment by FractusLogicum** [comment]
Wow that was fast! Thanks for getting back Jere.
I had it in Jobs [] section before but moved it to zone: [] a few days ago to see if it would behave differently.
It still triggers erratically at multiple times in a day despite have schedule: for 1:05am server time on a particular day of the month:
     e.g. on the 15th:
      schedule: 5 1 */15 * *

**Comment by IrcDirk** [comment]
I can confirm that zone jobs ignore "schedule".

**Comment by IrcDirk** [comment]
@JereKuusela

Seems that there is problem when there are multiple Zone jobs.

Each zone have its own timestamp written to file and its set to Now when one of Zone jobs is Executed. 
This seems fine but with multiple Zone jobs that might be a problem. 

Example:
- one Zone job is running every minute so the Zone timestamp is overwritten every minute
- another Zone job should be done every hour so it will not be executed because timestamp is updated every minute

So to fix this we need to write all Zone jobs timestamps for all Zones.
So if there are two Zone jobs Zone -1,2 need to have two timestamps.

Please correct me if im wrong.

**Comment by JereKuusela** [comment]
Cron runs at specific times, not at specific intervals. 

If your job should run at 12:00, only thing that matters is whether the timestamp is before or after 12:00.

If it's before, and current time is after, the job is done. Otherwise, the job is not done.

Timestamps of 11:30, 11:59 or even 11:59:59 would behave exactly the same.

**Comment by IrcDirk** [comment]
@JereKuusela 

Ok. So with this maybe im wrong, but then explain me this log:

> Feb  7 18:12:10 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Selected time zone Europe/Warsaw / CET.
> Feb  7 18:12:10 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Reloading 0 cron jobs.
> Feb  7 18:12:10 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Reloading 1 zone cron jobs.
> Feb  7 18:12:10 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Reloading 0 join jobs.
> Feb  7 19:25:15 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=3264.00,4416.00 max=150 force start
> Feb  7 20:17:45 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-5312.00,320.00 max=150 force start
> Feb  7 21:18:20 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-5312.00,320.00 max=150 force start
> Feb  7 21:22:35 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-5312.00,320.00 max=150 force start
> Feb  7 22:22:18 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=1344.00,4032.00 max=150 force start
> Feb  7 22:27:34 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-5312.00,320.00 max=150 force start
> Feb  7 23:22:39 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=1344.00,4032.00 max=150 force start
> Feb  7 23:58:02 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=1088.00,4608.00 max=150 force start
> Feb  8 00:22:38 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-2432.00,704.00 max=150 force start
> Feb  8 00:37:47 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=1088.00,4608.00 max=150 force start
> Feb  8 00:40:49 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=1344.00,4032.00 max=150 force start
> Feb  8 01:22:58 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-2432.00,704.00 max=150 force start
> Feb  8 08:41:00 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-5312.00,320.00 max=150 force start
> Feb  8 09:27:26 valheim-khc start_valw_bepinex.sh[639859]: [Info   :  Cron Job] Executing: zone_reset pos=-5312.00,320.00 max=150 force start
> 

My config:

> timezone: Europe/Warsaw
> interval: 60
> jobs: []
> zone:
>   - command: zones_reset pos=<x>,<z> max=150 force start
>     schedule: "22 * * * *"
>     avoidPlayers: true
>     locations: Eikthyrnir,GDKing,Bonemass,Dragonqueen,GoblinKing
> join: []
> logJobs: true
> logZone: true
> logJoin: true
> discordConnector: false

It should be running on every hour on the 22nd minute but it runs random times or am i missing something?

**Comment by JereKuusela** [comment]
Zone jobs run the next time that zone becomes active. That's why there is a command for each zone.

If you want to run a single job every hour, then put it as a general job instead.
