### ISSUE TITLE
parameter <name> not resolved in join job

### ISSUE THREAD

**Issue by daKeepa** [JereKuusela/valheim-cron_job#15]
added a simple join job based on example https://github.com/JereKuusela/valheim-cron_job/blob/main/README.md#player-greeting but the parameter <name> was not resolved with the player name but "name" as a string. Also tested with older format $name$, $name (found a corresponding hint on nexusmods), but they are 1:1 written in the message. parameters first and id also don't work...
is there a special file encoding required or what am I doing wrong?

**Comment by JereKuusela** [comment]
My mistake, should be fixed in version 1.7

**Comment by daKeepa** [comment]
a big thank you for the instant fix! worked like a charm
