### ISSUE TITLE
commands execution occurance

### ISSUE THREAD

**Issue by StellarwhimsRepo** [JereKuusela/valheim-cron_job#4]
edit: first awesome fix for the datetime thing!

This one is harder to describe. I will try to break it down as best as I observed it.

disclaimer: it has been a long time since i have seen a cron scheduler or worked with it or understood it.

it *seems* like commands are cached and all executed at the time a player logs in. resulting in redundant executions of the commands.

I believe this is because when zero player are logged in, no zones are active.  resulting in the server pausing. but scheduled commands are seeming to queue up.

what happens: if I log in my test character after a scheduled command is supposed to happen, very shortly after log in, the command executes every command entry I have in zone jobs (two) immediately. my jobs are set to fire off at two specific times of the day.

since I was logging in at 4:13 PM central time, I expected cronjob to do nothing. however ... I will let the screen shots do more talking.
![image](https://user-images.githubusercontent.com/8019709/208268438-b3beb79b-4574-4bd7-9b2d-06db67435430.png)
![image](https://user-images.githubusercontent.com/8019709/208268463-2fdd105d-1307-4cb7-83a3-bb4e5c8fbc3b.png)

**Comment by JereKuusela** [comment]
Your jobs have inactive: 60 which should make them run if the zone hasn't been visited for an hour. Could this cause that?

**Comment by StellarwhimsRepo** [comment]
so, on my test server nobody is visiting anything so it should run,  however, they are scheduled and the jobs were running not at the scheduled time.

**Comment by JereKuusela** [comment]
Zone jobs execute the next time someone is near the zone.
